DROP TABLE IF EXISTS notifikasi;
CREATE TABLE notifikasi(
id_notifikasi INT AUTO_INCREMENT PRIMARY KEY,
NIM CHAR(9),
NIDN CHAR(10),
pesan VARCHAR(100) NOT NULL,
tanggal_kirim DATE NOT NULL,
FOREIGN KEY (NIM) REFERENCES mahasiswa (NIM),
FOREIGN KEY (NIDN) REFERENCES dosen (NIDN)
);